name: practice
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.3.3
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  provider: ^6.0.1
  logger: ^1.1.0
  recase: ^4.0.0
#  dio_log: ^5.3.0+3
  collection: ^1.15.0
  go_router: ^13.2.1
  envied: ^0.5.2
  auto_size_text: ^3.0.0
  flutter_keyboard_visibility: ^6.0.0
#  flutter_performance_pulse: 1.0.5
  # For charts and visualizations
  fl_chart: ^0.66.2
  # For isolate computations
  compute: ^1.0.2
  # For device info
  device_info_plus: ^9.1.2
  # For battery info
  battery_plus: ^5.0.3
  # For local storage
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  talker_dio_logger: 4.4.7
  talker_flutter: 4.4.7
  bot_toast: ^4.1.3
  package_info_plus: ^8.1.2
  connectivity_plus: ^6.1.1
  flutter_timezone: ^1.0.8
  json_annotation: ^4.9.0
  performance_monitor:
    path: plugins/performance_monitor

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.4.8
  go_router_builder: ^2.4.1
  envied_generator: ^0.5.2
  json_serializable: ^6.9.0
  patrol: ^3.11.1
flutter:
  uses-material-design: true

  assets:
    - assets/images/

patrol:
  app_name: practice
  android:
    package_name: com.example.practice
  ios:
    bundle_id: com.example.practice
  macos:
    bundle_id: com.example.practice